### ISSUE TITLE
Upgrade to Bootstrap 3

### ISSUE THREAD

**Issue by johnwoltman** [m0r13/mclogalyzer#11]
I'd like the mclogalyzer template to be upgraded to Bootstrap 3.  With BS3 it's easier to make mobile sites.  I upgraded my fork of this repo, and will make a PR based on it.  But a problem is that the the navigation that uses javascript doesn't work well on mobile devices (particularly iPhones/iPads).  In my fork I removed the javascript navigation and use old-style anchor tags with links based on IDs.

Is that acceptable?

**Comment by m0r13** [comment]
I already upgraded to Bootstrap 3 yesterday. If the navigation works the same way with that old-style thing, that should be okay.

**Comment by johnwoltman** [comment]
I hadn't noticed because I was working on my own branch.  I merged your changes back into my fork.
