### ISSUE TITLE
Last login date column (feature request)

### ISSUE THREAD

**Issue by n0ct** [m0r13/mclogalyzer#9]
I would like to have the last login date in the program's columns.

**Comment by greggubben** [comment]
I am not sure I understand.  
Last Login is a column already available on the Players tab.  It can be added from the list of available columns on the left.
Do you want it shown in the table by default?

**Comment by n0ct** [comment]
I didn't see "last login date" column in the demo ( http://89.22.96.50/~minecraft/teststats.html# ) but maybe it is not up to date ? You can mark that issue as resolve if it is now an available command.

Thank you.

**Comment by m0r13** [comment]
The demo is a bit outdated. I will update it.
